x-networks: &networks
  networks:
    - default
x-labels: &enable_traefik
  labels:
    - traefik.enable=true
x-restart: &restart
  restart: unless-stopped

services:
  minio:
    <<: [*networks, *enable_traefik, *restart]
    image: minio/minio${MINIO_TAG:?}
    container_name: minio
    volumes:
      - ./data:/data:z
    ports: 
      - 0.0.0.0:9000:9000
    # We use traefik for access to minio
    #  - 0.0.0.0:9001:9001
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}

networks:
  default:
    name: ${MYNET:?}
    external: true
