x-networks: &networks
  networks:
    - default

services:
  postgres:
    <<: *networks
    image: postgres${SERVICE_TAG:?}
    container_name: postgres
    ports:
      - ${POSTGRESQL_PORT:-0.0.0.0:5432}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:?}
      TZ: ${TIMEZONE:-UTC}
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  default:
    name: ${MYNET:?}
    external: true
